---
- name: Create user and group
  hosts: localhost
  tasks:
   - name: Create group
     group:
       name: "{{ item }}"
       state: present
     loop:
       - testers 

   - name: Create User
     user: 
       name: "{{ item }}"
       state: present
       password: "{{ airgear1-q | password_hash('sha512') }}"
       shell: /bin/bash
       group: "{{ testers }}"
     loop:
       - Dima

